# Generated by Django 5.2.7 on 2025-11-10 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Part Number')),
                ('make', models.CharField(max_length=100, verbose_name='Make/Manufacturer')),
                ('grade', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('MILITARY', 'Military'), ('SPACE', 'Space')], max_length=20, verbose_name='Grade')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], max_length=10, verbose_name='Condition')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=50, unique=True, verbose_name='Process ID')),
                ('process_name', models.CharField(max_length=200, verbose_name='Process Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['process_id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, unique=True, verbose_name='Project ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='FailureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(choices=[('PART', 'Part'), ('PROCESS', 'Process')], max_length=10, verbose_name='Failure Type')),
                ('failure_date', models.DateTimeField(verbose_name='Failure Date & Time')),
                ('failure_description', models.TextField(verbose_name='Failure Description')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('root_cause', models.TextField(verbose_name='Root Cause')),
                ('failure_confirmation', models.TextField(verbose_name='Failure Confirmation')),
                ('action_taken', models.CharField(choices=[('REPAIR', 'Repair'), ('REWORK', 'Rework')], max_length=10, verbose_name='Action Taken')),
                ('preventive_measures', models.TextField(verbose_name='Preventive Measures')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='records.part', verbose_name='Part')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='records.process', verbose_name='Process')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='records.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Failure Record',
                'verbose_name_plural': 'Failure Records',
                'ordering': ['failure_date'],
            },
        ),
    ]
